#! /bin/sh

usage() {
	echo "Usage: $0 [proposal_id] (-l|--list|-v|--view|-h|--help)"
}

if [ $# -eq 0 ]
then
	usage
	exit 1
fi

if [ $# -eq 1 ]
then
	case $1 in
		-l|--list)
			echo "Content-Type: application/json"
			echo ""
			echo -n "["
			for path in `ls /usr/share/tiva/proposals`
			do
				[ -f "/usr/share/tiva/proposals/$path" ] && echo -n "\"$path\","
			done
			echo "\b]"
			exit 0
		;;
		-v|--view)
			echo "Content-Type: text/html"
			echo ""
			echo ""
			exit 0
		;;
		-h|--help)
			usage
			exit 0
		;;
		*)
			usage
			exit 1
		;;
	esac
fi

if [ $# -eq 2 ]
then
	proposal_id=$1
	case $2 in
		-l|--list)
			echo "Content-Type: application/json"
			echo ""
			echo "[]"
			exit 0
		;;
		-v|--view)
			echo "Content-Type: text/html"
			echo ""
			echo "<p>"
			cat /usr/share/tiva/proposals/$proposal_id
			echo "</p>"
			exit 0
		;;
		-h|--help)
			usage
			exit 0
		;;
		*)
			usage
			exit 1
		;;
	esac
fi

if [ $# -gt 2 ]
then
	usage
	exit 1
fi
