#! /bin/sh

check_signatures()
{
	for filename in `ls /usr/share/tiva/proposals`
	do
		[ -f /usr/share/tiva/proposals/$filename ] || continue
		[ `cd /usr/share/tiva/proposals && /usr/local/bin/odverify -p $filename | wc -l` -eq 1 ] || continue
		execute_proposal $filename
	done
}

execute_proposal()
{
	/usr/share/tiva/proposals/$1 1> /usr/share/tiva/acts/log/$1.out 2> /usr/share/tiva/acts/log/$1.err
	mv /usr/share/tiva/proposals/$1 /usr/share/tiva/acts/$1
}

run()
{
	while true
	do
		check_signatures
		sleep 1
	done
}

run &
